### ISSUE TITLE
Persisting Login between Page Refreshes Issue...

### ISSUE THREAD

**Issue by timothykrichards** [joeeames/MEANAppsFiles#10]
Hi Joe,

I'm going through your course and it's great!

I've run into an issue that I'm hoping you can direct me toward a solution.

I'm going through the "Persisting Login between Page Refreshes" video in the "Security and Authorization" section of your course and am at the part where I change the code in routes.js from "res.render('index')" to res.render('index', {bootstrappedUser: req.user}).

When I go to refresh the page it renders the following:

ReferenceError: req is not defined
at C:\Dev\FireflyXP\server\config\routes.js:25:25
at Layer.handle [as handle_request] C:\Dev\FireflyXP\node_modules\express\lib\router\layer.js:82:5)
at next (C:\Dev\FireflyXP\node_modules\express\lib\router\route.js:110:13)
at Route.dispatch (C:\Dev\FireflyXP\node_modules\express\lib\router\route.js:91:3)
at Layer.handle [as handle_request] C:\Dev\FireflyXP\node_modules\express\lib\router\layer.js:82:5)
at C:\Dev\FireflyXP\node_modules\express\lib\router\index.js:267:22
at Function.proto.process_params C:\Dev\FireflyXP\node_modules\express\lib\router\index.js:321:12)
at next (C:\Dev\FireflyXP\node_modules\express\lib\router\index.js:261:10)
at SendStream.error (C:\Dev\FireflyXP\node_modules\express\node_modules\serve-static\index.js:107:7)
at SendStream.emit (events.js:95:17)

it seems to be having a problem with the req.user variable.  Any ideas on what may be wrong?

**Comment by timothykrichards** [comment]
I figured out the problem.  I fat fingered the req in the function call.

**Comment by joeeames** [comment]
good to hear!
