### ISSUE TITLE
Issues with testing chapter

### ISSUE THREAD

**Issue by tnwo** [joeeames/MEANAppsFiles#14]
Immediately after installing the devDependencies in the testing chapter, this pops up in Webstorm:

![screen shot 2015-06-23 at 11 19 05](https://cloud.githubusercontent.com/assets/6314824/8304108/3d4e9a98-199b-11e5-8ec6-6cbc111f42be.png)

And when I run 'karma start' I get this:

![screen shot 2015-06-23 at 11 24 42](https://cloud.githubusercontent.com/assets/6314824/8304112/46c7d21a-199b-11e5-8c54-2b73bf998ec3.png)

**Comment by joeeames** [comment]
Going to close this issue. Hope you fixed the issue. For stuff like this in general please post in the discussion forums. I'm a lot more active on there.
