### ISSUE TITLE
where can i get the finished version of the course?

### ISSUE THREAD

**Issue by ronca85** [joeeames/MEANAppsFiles#16]
can you provide a working version of this course? i was unable to get the user login to work and i would like to compare the files to see what i did wrong. i don't know how many times i went through the videos... it should work but it doesn't. i'm getting a 500 internal server error for some reason.

**Comment by eriksjaastad** [comment]
It might be that you're using newer versions. Check the version numbers of your modules.

**Comment by sislandemarcos** [comment]
Not this one?
https://app.pluralsight.com/library/courses/building-angularjs-nodejs-apps-mean/table-of-contents

**Comment by joeeames** [comment]
@ronca85 just added it to the repo.
