### ISSUE TITLE
using html instead of jade

### ISSUE THREAD

**Issue by HamzaJridi** [joeeames/MEANAppsFiles#17]
Hi, I have been following this tutorial and I tried to use html instead of Jade, right now I'm stacked in the persist login between page refreshes because you used a jade feature that cannot be used in html, can you suggest a method to be used to persist the user login please ?

**Comment by joeeames** [comment]
since there is some server-side rendered stuff, you have to use some kind of templating language on the server. EJS is probably the most popular node templating language. I would start there.
