### ISSUE TITLE
Reference error and mvNavBarLoginCtrl.js issue

### ISSUE THREAD

**Issue by dbwebconsulting** [joeeames/MEANAppsFiles#18]
Joe,
After completing the "Adding the login display" module in Authentication I am encountering an issue with jquery. The error is:
ReferenceError: define is not defined, jquery.js line 1
define(['./core',
'./selector',
'./traversing',
etc...
], function (jQuery) {
'use strict';
return (window.jQuery = window.$ = jQuery);
});

The console.log("I'm not done yet."); from mvNavBarLoginCtrl.js is also not rendering.
I have tried googleing this issue to no avail. My jquery.js version is 3.1.0 installed globally.
Thanks,
Dave

**Comment by joeeames** [comment]
looks like you installed the AMD version of jQuery. you want the browser version of it. I tried installing it through npm and didn't get the AMD version. Try using the CDN version here: https://code.jquery.com/jquery-3.1.0.min.js or download the file from somewhere listed here: https://jquery.com/download/ or use bower to install. Please verify this addresses your issue so I can close this.

**Comment by dbwebconsulting** [comment]
Joe,
I found the issue. In /server/includes/scripts.jade I was referencing the wrong jquery.js file. I was pointing to /vendor/jquery/**_src_**/jquery.js instead of /vendor/jquery/**_dist_**/jquery.js.

thanks,
Dave

**Comment by joeeames** [comment]
good deal
