### ISSUE TITLE
Persisting Login Between Page Refresh

### ISSUE THREAD

**Issue by ElliotPsyIT** [joeeames/MEANAppsFiles#4]
Hi Joe - I'm working through your MEAN stack pluralsight course.  It's excellent and I'm learning a ton.  

I have a question about the bootstrapped user approach in the case where the server is re-started.  It happened during your course when nodemon re-started the server even though you changed only client code.  When the server was re-started, it left a desynchronized state with the client.  There was an authenticated user on the client but no authenticated user on the server.  You recognized this and then manually logged in again.  But considering a live scenario, at that point routing on the client would have failed since the data requests to the server would be rejected on routes requiring an authenticated user.

Am I missing something in my representation of this scenario (the effect of re-starting the server where there is an active client)?  If I've got this right, I wonder how you think about handling that case yet still want to bootstrap a user for login persistence across page refreshes?

Thanks again for your exceptional set of pluralsight courses!

Elliot

**Comment by joeeames** [comment]
Doing some housecleaning. Gonna close this issue. If the original issue persists, please post in the forums. For the second comment, great idea, I'll keep that in mind.
