### ISSUE TITLE
bodyParser constructor deprecated

### ISSUE THREAD

**Issue by schottyd** [joeeames/MEANAppsFiles#7]
Hi, 

I'm struggling to follow along ... probably need to go back and do more work on the fundamentals as there is a lot of new material in here for me.

Meantime: It seems that bodyParser has been deprecated. A google search suggested replacing the app.use(bodyParser()) statement as follows. 

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({
    extended: true
}));

Should this work? I don't seem to be getting the CSS files delivered when I look at it after step "Creating a Layout" and by time I've followed "Creating the Angular Application", I'm not getting the main-content delivered. The only difference I can spot from the tutorial code and my code is the section above ...

Thanks for the advice,

David

**Comment by joeeames** [comment]
You definitely want to make this change. If you look in the discussion for the course, this is noted quite a bit. (always a good idea to check there first for issues like this) I'm in the middle of updating the course, and updates should be out in a week or two.

I honestly am not sure why you aren't getting files delivered or the main content. That shouldn't be happening even without this change. you may want to go back through and be sure to follow along exactly. every time there's a problem, it's that something got missed when following along.
