### ISSUE TITLE
Root Path Issue

### ISSUE THREAD

**Issue by MemoryChips** [joeeames/MEANAppsFiles#9]
I had to modify this line in config.js by adding another ../
  rootPath = path.normalize(__dirname + '../../../');

rootPath becomes:
{ rootPath: '/home/rob/Documents/CodeSchoolNotes/MeanStack/MultiVision/',
  db: 'mongodb://localhost/multivision',
  port: 3030 }

instead of:
{ rootPath: '/home/rob/Documents/CodeSchoolNotes/MeanStack/MultiVision/server/',
  db: 'mongodb://localhost/multivision',
  port: 3030 }

I am surprised no one else seems to have this issue.

Rob

**Comment by joeeames** [comment]
Rob, doing some housecleaning. Going to close this issue. If you need any more help, throw a comment in the forums or maybe open a new issue.
